### PR TITLE
7.x 3.x art unlisted events

### PR DESCRIPTION
**Pull request by jbickar**
@sherakama plz merge

### CODE REVIEW

**Comment by sherakama** [comment]
@jbickar, we will need to be able to revert this feature in order to get it up to snuff. I have merged in the latest from the art site. Are you planning on also providing the latest changes to the manage content form? I think those changes would be handy.

**Comment by jbickar** [comment]
Forgot about the manage events view. Yeah, I can do that.

**Comment by jbickar** [comment]
Should be ready to go now with the Manage Events View

**Comment by sherakama** [comment]
The featured and associated program fields should be maintained. Please restore them.

**Comment by jbickar** [comment]
Probably best thing to do would be to have @cjwest build out the new functionality for the View on the art website (since this came from a clean install) and then export that View.

**Comment by sherakama** [comment]
We are close. We just need to keep those two fields in the manage content view. We just need to merge in the new changes and leave the featured and associated fields alone.

**Comment by sherakama** [comment]
@jbickar 
I have mashed the two views together. Please pull down the latest code on to a fresh copy of the art site and revert the events features to test.

Thanks,

**Pull request merged**
