### PR TITLE
Change past events filter from <= to <

### PR DESCRIPTION
**Pull request by cjwest**
#  READY FOR REVIEW

# Summary
- This PR is in response to [issue #80](https://github.com/SU-SWS/stanford_events_importer/issues/80).  I adjusted the operator on the filter for the Past Event page from <= to <. Thereby stopping events that happen now or today from appearing on the Past Events page.

# Needed By (Date)
- When possible

# Criticality
- Fixes broken stuff

# Steps to Test
- Switch to this branch
- Flush cache
- Create a test event that happens today
- Navigate to `events/upcoming-events` 
- Verify you see your test event
- Navigate to `events/past-events`
- Verify you _don't_ see your test event

# Affects 
- All products

# Associated Issues and/or People
## Related Issue
https://github.com/SU-SWS/stanford_events_importer/issues/80

## Folks to notify
@eolienne 

# See Also
- [PR Checklist](https://gist.github.com/sherakama/0ba17601381e3adbe0cad566ad4d80a5)

### CODE REVIEW

**Comment by sherakama** [comment]
This makes sense to me. Let's have one more reviewer before we accept.

**Review by sherakama — APPROVED** [review]

**Comment by sherakama** [comment]
@jbickar please see the comments in #80 
I think this is a good change.

**Comment by jbickar** [comment]
cant-someone-else-do-it

**Comment by jbickar** [comment]
OK, **FINE**

**Comment by jbickar** [comment]
I can't reproduce the bug reported in #80 with the current `7.x-3.x` branch:

1. It's 1:45PM
2. I created an event for today at 1:50PM, with no end date
3. I cleared caches
4. It appeared at `events/upcoming-events`
5. It did **not** appear at `events/past-events`
6. I updated my event to start today at 1:20PM
7. I cleared caches
8. It appeared at `events/upcoming-events
9. It did **not** appear at `events/past-events`

**Comment by jbickar** [comment]
Oh, hm. JS+ doesn't use that same View at `events/past-events`? What site(s)/product(s) are you seeing this on, @cjwest and @eolienne ?

**Comment by eolienne** [comment]
@jbickar I saw this on ethicsinsociety.stanford.edu, which is jumpstart academic

**Comment by jbickar** [comment]
Granularity changed as well in 2c698bce363273a29511cb201d7c029b2178bceb.

Back to @sherakama for review.

**Review by sherakama — APPROVED** [review]

**Pull request merged**
